"""
DDL Generation Database Model

Tracks DDL statements generated by the system with validation scores and approval status.
"""

from sqlalchemy import Column, Integer, String, Text, Float, ForeignKey, JSON
from sqlalchemy.orm import relationship
from src.models.base import Base, TimestampMixin


class DDLGeneration(Base, TimestampMixin):
    """
    DDL generation tracking table.

    Stores all DDL statements generated by the system, including validation scores,
    human feedback, and approval status.
    """

    __tablename__ = "ddl_generated"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to metadata
    metadata_id = Column(Integer, ForeignKey("metadata_extract.id"), nullable=False, index=True)

    # LangGraph thread ID for tracking conversation history
    thread_id = Column(String(128), nullable=False, index=True)

    # Generated DDL statement
    ddl_statement = Column(Text, nullable=False)

    # S3 path where DDL file is stored
    ddl_file_path = Column(String(512), nullable=True)

    # Validation scores
    validation_score = Column(Float, nullable=True)  # sqlparse validation score (0-1)
    accuracy_score = Column(Float, nullable=True)  # Accuracy vs metadata (0-1)

    # Validation details (JSON with specific validation results)
    validation_details = Column(JSON, nullable=True)

    # Human-in-the-loop feedback
    feedback_iteration = Column(Integer, default=0, nullable=False)  # Number of feedback iterations
    user_feedback = Column(Text, nullable=True)  # Latest feedback from user

    # Status: 'pending', 'approved', 'rejected', 'regenerating'
    status = Column(String(32), default='pending', nullable=False, index=True)

    # Relationships
    metadata_extract = relationship("MetadataExtract", back_populates="ddl_generations")

    def __repr__(self):
        return f"<DDLGeneration(id={self.id}, metadata_id={self.metadata_id}, status='{self.status}')>"
