"""
Synthetic Data Generation Database Model

Tracks synthetic test data generated by the system with validation scores and approval status.
"""

from sqlalchemy import Column, Integer, String, JSON, Float, Text, ForeignKey
from sqlalchemy.orm import relationship
from src.models.base import Base, TimestampMixin


class SyntheticDataGeneration(Base, TimestampMixin):
    """
    Synthetic data generation tracking table.

    Stores all synthetic test data generated by the system, including validation scores,
    human feedback, and approval status.
    """

    __tablename__ = "testdata_generated"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to metadata
    metadata_id = Column(Integer, ForeignKey("metadata_extract.id"), nullable=False, index=True)

    # Optional: Foreign key to DDL generation (if data is generated based on approved DDL)
    ddl_id = Column(Integer, ForeignKey("ddl_generated.id"), nullable=True, index=True)

    # LangGraph thread ID for tracking conversation history
    thread_id = Column(String(128), nullable=False, index=True)

    # S3 path where synthetic data file is stored
    file_path = Column(String(512), nullable=True)

    # Generated synthetic data (JSON with HDR/BDY/TLR structure)
    synthetic_json = Column(JSON, nullable=False)

    # Data statistics
    row_count = Column(Integer, nullable=True)

    # Data type: 'edge', 'boundary', 'happy_path', 'negative'
    data_type = Column(String(32), nullable=True)

    # Validation score
    validation_score = Column(Float, nullable=True)

    # Validation details (JSON with specific validation results)
    validation_details = Column(JSON, nullable=True)

    # Human-in-the-loop feedback
    feedback_iteration = Column(Integer, default=0, nullable=False)
    user_feedback = Column(Text, nullable=True)

    # Status: 'pending', 'approved', 'rejected', 'regenerating'
    status = Column(String(32), default='pending', nullable=False, index=True)

    # Relationships
    metadata_extract = relationship("MetadataExtract", back_populates="synthetic_data_generations")
    ddl_generation = relationship("DDLGeneration", backref="synthetic_data_generations")

    def __repr__(self):
        return f"<SyntheticDataGeneration(id={self.id}, metadata_id={self.metadata_id}, status='{self.status}')>"
